// store layout

const store = {
    users: {
        id: { //userId
            id: String,
            name: String,
            avatarURL: String,
            answers: {
                qId: "optionOne or optionTwo", //question ID
                qId: "etc...",
            },
            questions: [qId, qId],
        },
        id: {}, //etc...
    },
    
    questions: {
        qId: { //question ID
            id: qid, //question ID
            author: userId,
            timestamp: Date.now(),
            optionOne: {
                votes: [userId, userId], //list of users who voted for this option
                text: "string of first option text"
            },
            optionTwo: {
                votes: [userId, userId], //list of users who voted for this option,
                text: "string of second option text"
            }
        },
        qId: {}, //etc...
    },
    authedUser: userId,
};

// ID's generated by this func
// makes a 22 char base 36 id - collisions are possible but very unlikely
// can implement a check for key === undefined before adding to store
// if not undefined, regenerate id
function generateUID () {
  return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)
}